spring.application.name=copilot3DX

# ==========================================
# SERVER
# ==========================================
server.port=9090

# ==========================================
# 3DEXPERIENCE
# ==========================================
threedx.tenantid = R1132101389013

threedx.passport-url=https://r1132101389013-eu1.iam.3dexperience.3ds.com

threedx.space-url=https://r1132101389013-eu1-space.3dexperience.3ds.com/enovia

threedx.username=sammy.ben-salah@keonys.com
threedx.password=Admin123!

threedx.security-context=VPLMProjectLeader.Company%20Name.ATR
