spring.application.name=copilot3DX

# ==========================================
# SERVER
# ==========================================
server.port=9090

# ==========================================
# 3DEXPERIENCE
# ==========================================
threedx.tenantid = R1132101389013
threedx.passport-url=https://r1132101389013-eu1.iam.3dexperience.3ds.com
threedx.space-url=https://r1132101389013-eu1-space.3dexperience.3ds.com/enovia
threedx.username=20272d54-4914-4b62-865a-f7360a0e837e
threedx.password=sEUf%o^GUY%hr_>3Kow-.!Q9
threedx.security-context=VPLMProjectLeader.Company%20Name.ATR

# ==================================================
# MCP SERVER
# ==================================================

spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.name=3DX-MCP
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp
